name: Demo delete
on:
  delete:
    branches:
      - demo**

jobs:
  branch-delete:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/next-app-demo-delete.yaml@main
    secrets: inherit
    with:
      app: sykmeldinger
      base-path: /syk/sykmeldinger
